### ISSUE TITLE
PHP Notice: Undefined index: module in feeds_system_info_alter() (line 896

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#106]
This PHP notice is appearing for all feeds plugins defined by feeds module. 
```
Notice: Undefined index: module in feeds_system_info_alter() (line 896 of /Users/jlampton/Sites/fibonacci/militants/backdrop/docroot/modules/feeds/feeds.module).
```

**Comment by jenlampton** [comment]
I could have sworn I'd filed a PR for this before, but I can't find it, so here it is again :) 
https://github.com/backdrop-contrib/feeds/pull/107

**Comment by stpaultim** [comment]
@jenlampton - Are you thinking of this one?

https://github.com/backdrop-contrib/feeds/issues/13

**Comment by stpaultim** [comment]
I have a site with the same errors. This patch is not fixing it. I also tried the patch for #13 and it didn't help either. This site has a bunch of modules enabled.

**Comment by argiepiano** [comment]
This PR fixes the problem with feed plugins provided by `feeds`. There are other projects that provide other feed plugins - those other modules should also add the key `'module'` to the plugin definition.

@stpaultim -  a quick way to find out which project(s) is/are creating this issue is to:

1. Apply this patch (clear caches twice or even three times). If you still see the error: 
2. Enable Devel
3. run `dpm(feeds_get_plugins())`;
4. Inspect the resulting array looking for plugins that don't have the module key in their definitions

Take note of the plugin name (they usually start with `'Feeds...'`), find which module provides it, and file an issue in their queues.

**Comment by argiepiano** [comment]
BTW, you have to clear cache TWICE after applying the patch. The plugins with the 'module' key are cached after the problematic line that produces the warning is run. The second cache clear after applying the patch shouldn't produce any notices IF you don't have another module that's defining additional feed plugins

**Comment by stpaultim** [comment]
I traced my problem to the following module: JSONPath Parser

The problem appears to be fixed in DEV branch, but fix has not been released.

@argiepiano - Thanks for the steps to trace to the problem. This worked perfectly for me.
