### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in FeedsNodeProcessor->clean()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#130]
I'm seeing this in my logs a lot:

> Warning: count(): Parameter must be an array or an object that implements Countable in FeedsNodeProcessor->clean() (line 481 of /app/modules/contrib/feeds/plugins/FeedsNodeProcessor.inc).

**Comment by herbdool** [comment]
@laryn the line is `$total = count($state->removeList);`. Must be happening because `$state->removeList` is NULL or something. Could wrap it in `if (!empty($state->removeList)) {` like what I see in `FeedsUserProcessor`). If you've got a moment can you create a PR for that?

I've set up this project so it requires someone to review the PR before it can be merged.

**Comment by MegaChriz** [comment]
See also https://www.drupal.org/project/feeds/issues/3337811

**Comment by herbdool** [comment]
I'm just reading my previous comment. Seems like I forgot to add a PR? At any rate, thanks for the heads-up @MegaChriz. I think we can just port over the D7 patch.

**Comment by herbdool** [comment]
I've created a PR matching the one here https://www.drupal.org/project/feeds/issues/3337811#comment-14999388.
So just a fix, no tests.
