### ISSUE TITLE
Fatal Error on initial feed creation

### ISSUE THREAD

**Issue by joetri** [backdrop-contrib/feeds#143]
I'm working on a transition from D7 to Backdrop.  I had a couple of feeds active in the old D7 site.  I'm just getting around to getting those replicated in Backdrop after addressing other issues.  (So there is possibly some old cruft in the DB for the old D7 feeds?)

I installed and enabled 1.x-1.1.5 version of Feeds, Feeds Admin UI and Feeds Import and Job Scheduler 1.x-1.1.4 modules via the project installer.

When attempting to create my first feed at  https://mywebsite.org/admin/structure/feeds/create I got the following error: "Fatal error: Class name must be a valid object or a string in /home/mywebsite/dev/modules/feeds/includes/FeedsConfigurable.inc on line 73".  I tried multiple times with simple one word Name and Description fields: nothing exotic.

Line 73 reads: " $instances[$class][$id] = new $class($id);"

My Backdrop version is 1.26.3.
PHP version 5.6.40.
Bee status lists Drupal Compatability on.
"bee ws" reports nothing amiss.

What did I bozo?  Thanx All.  Backdrop on.

**Comment by laryn** [comment]
Hi @joetri -- not sure about the particular issue, but if you're worried about cruft in the database, have you tried complete uninstall of Feeds and then re-enabling it before trying this?

EDIT: I just tried to create a feed on a D7 upgrade site in development, and had no issues. (PHP 8.1 though)

**Comment by joetri** [comment]
Thanx for quick response Laryn.  What would "complete uninstall of Feeds" entail?  Removal of tables at the DB level?
I searched for the mod in the modules gui and found nothing, so did the install.  (I was a bit surprised it hadn't made it into core.)

**Comment by argiepiano** [comment]
@joetri, this is a theory of what may have happened. It may be completely wrong ;-) But perhaps some version of this is true. 

1. You may have disabled but did not uninstall  Feeds in the D7 site - this caused the D7 database to contain all the feeds definitions/configurations, even though the Feeds module was disabled in D7
2. Since Feeds was disabled in D7, Backdrop did not enable Feeds when you upgraded, and therefore the Backdrop upgrade hooks foir Feeds did not run
3. Then you enabled Feeds in the Backdrop site - this may have caused the error, since no upgrade hooks for Feeds run in the first place, and the definitions were in the original DB

So, I'd try this:
1. Start again
2. Be sure Feeds is enabled in the D7 site
3. Be sure Feeds is present in the BAckdrop `modules` folder
4. Run the whole upgrade from scratch and check to see if there are any error.
5. If not, then the feeds got upgraded

EDIT: also check that any Feeds submodules in the D7 site exist in the BAckdrop modules folder too

**Comment by laryn** [comment]
@joetri If you disable the module, there is one additional step to uninstall it at **admin/modules/uninstall**, and the module should clean up after itself and remove database tables, etc.

I'm not sure what stage you are at, but if you are still pre-upgrade, then it may make sense to start where @argiepiano suggests. If the upgrade already happened and you're moving forward from this point, try my suggestion.

**Comment by joetri** [comment]
@laryn Thanx!  That did it.
Followed your advice on the uninstall and that did the trick.  I suppose that cleaned up any old crufty tables.
@argiepiano good suggestions, but the transition to Backdrop has happened so there's no going back!

**Comment by joetri** [comment]
Should I close this out at this point? Happy to blame this on operator error (me!), but might be good on install to check that things are really clean and pristine: no old feeds table data.

**Comment by laryn** [comment]
@joetri I'd say probably okay to close. The issue being that sometimes enabling the module when you have tables with data (for example, you've disabled the module but not fully uninstalled it) is what you want -- and you really don't want those to be deleted unexpectedly if they are valid. I think the fact that it happened in this particular way with the upgrade in the middle is what was the issue here.

**Comment by joetri** [comment]
Makes sense.  Closing.  Thanx all.
