### ISSUE TITLE
PHP 8.2: Creation of dynamic property FeedsHTTPCacheItem::$code is deprecated

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#148]
PHP 8.2 compatibility issues:
I'm running a feeds import using the feeds_jsonpath_parser module, and I get two feeds related errors during the import.

The first error is
```
Creation of dynamic property FeedsHTTPCacheItem::$code is deprecated
```

**Comment by herbdool** [comment]
I can't figure out what might be setting `$code` in `FeedsHTTPCacheItem`. There's nothing that I can find in Feeds. Is `feeds_jsonpath_parser` trying to set it? Are you able to replicate the error with just Feeds enabled?

**Comment by herbdool** [comment]
Oh I think it's happening in `feeds_http_request`. It's creating `$result` as a `stdClass()` and adding code, error, data, etc, to it. I'm guessing that sometimes that it ends up being a cache item rather than an http request. So maybe we can just add some properties. Or exempt that class from checking, like we've done elsewhere.

**Comment by herbdool** [comment]
I've added the `#[AllowDynamicProperties]` attribute to the class.
