### ISSUE TITLE
Update README to list maintainers, license, etc

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/feeds#4]

**Comment by Al-Rozhkov** [comment]
I want to report that I tested Feeds in different combinations and I was able to break things just once. And it is already fixed in current 1.x branch.

I have imported about 20000 nodes with XML and CSV parsers. These nodes contain fields of the following types:

- boolean
- number (integer)
- text (short)
- text (long with summary)
- list (text)
- date
- image
- file (remote files was fetched saved to server)
- taxonomy term

Node properties (published, created) and file properties (alt, title, description) also was filled without problem.

I have ported [Feeds XPath Parser](https://www.drupal.org/project/feeds_xpathparser) module (coming soon in contrib) and Feeds works with XML XPath parser as well.

I just want to thank @docwilmot for porting this and propose to rid of the notice in README: `Early work on Drupal Feeds module. CSV and node import works, but not fully tested. Use at own risk.`

Lets add maintainers :)

**Comment by docwilmot** [comment]
thanks @Al-Rozhkov. Pushed a beta release.

**Comment by docwilmot** [comment]
Did you want to be listed as a maintainer?

**Comment by Al-Rozhkov** [comment]
No, I'm not ready to maintain such a complex module like Feeds. Maybe someday :smile:
