### ISSUE TITLE
PHP notice: Undefined index: disabled in feeds_load_importer_object()

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/feeds#46]
My error log is being flooded with thousands of entries like this one:
> Notice: Undefined index: disabled in feeds_load_importer_object() (line 1421 of [...]/modules/feeds/feeds.module).

A workaround might be to replace
`$object->disabled = $data['disabled'];`
with something like
`if (isset($data['disabled'])) {
  $object->disabled = $data['disabled'];
}`

**Comment by herbdool** [comment]
This is happening because we finally got the "disabled" property working and now if a feed was added before then it won't have it set. A quick fix for you may be to just resave your feeds with no changes. I think that would do the trick.

That won't be the best approach. I'm thinking `$object->disabled` needs to default to false and then set it with the actual data if it exists.

**Comment by sternhagel** [comment]
@herbdool Thanks, you're right - after saving the feed again the message doesn't show up anymore.
