### ISSUE TITLE
Error: Class 'FeedsConfigurable' not found

### ISSUE THREAD

**Issue by openskeptic** [backdrop-contrib/feeds#95]
When trying to enable Feeds module I get this error "Class 'FeedsConfigurable' not found" after clicking on the "Save Configuration" button. This fatal error means the module is not enabled.

**Comment by laryn** [comment]
I ran into this as well on a sandbox copy site and couldn't figure out why. I had installed it without an issue, then uninstalled (or refreshed from live) and got this error. I ended up having to do a complete refresh, deleting the filesystem and recopying everything from the live site, emptying config and refreshing from live, dropping the database and refreshing from live, then I could install and use Feeds again...

**Comment by argiepiano** [comment]
I'm finding this issue on a site that had Feeds, then got fully uninstalled, and installed again. What a hassle.

**Comment by argiepiano** [comment]
Ok this is happening because there is a call to `feeds_importer_load_all()` in file `feeds.install` (in `feeds_requirements()`. 

The problem is that that function ends up calling a static method of class `FeedsConfigurable`. In D7, the file that contains that class was always loaded through `files[]` in the `info` file. In Backdrop, in normal operation, that file is loaded through hook_autoload_info(). Except that THAT autoload hook is never invoked before running `feeds_requiremens()`. Result: the class is never found, and fatal error.

Solution: include `inculdes/FeedsConfigurable.inc` inside `feeds_requirements()`.

**Comment by argiepiano** [comment]
Additional info: this error happens in very specific conditions that are pretty unusual:
1. You have created a feeds importer
2. You disable and uninstall Feeds
3. For some reason that config file with the feed importer was either not removed (b/c of error), or moved manually (by moving the file) to the config folder

So, this sequence is actually not "normal", so I'm not sure if this fix is necessary. I submitted a PR anyway.

I see there is a test failure, but don't have time to check it.

Incidentally, even though I'm part of the Bug squad, I've lost the ability to review and/or merge PRs here. (Not that I was intending to use that here!).
